### Heroes Of Pymoli Data Analysis
* Of the 1163 active players, the vast majority are male (84%). There also exists, a smaller, but notable proportion of female players (14%).

* Our peak age demographic falls between 20-24 (44.8%) with secondary groups falling between 15-19 (18.60%) and 25-29 (13.4%).  
-----

### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [20]:
# Dependencies and Setup
import pandas as pd
import numpy as np
%config IPCompleter.greedy=True

# File to Load (Remember to Change These)
purchase_data = "purchase_data.csv"

# Read Purchasing File and store into Pandas data frame
purchase_data_df = pd.read_csv(purchase_data)

## Player Count

* Display the total number of players

In [21]:
purchase_data_df.head()

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44

In [22]:
player_count = (purchase_data_df["SN"].value_counts())
player_count.sum()

780

In [23]:
unique_player = purchase_data_df["SN"].unique()
unique_player

array(['Lisim78', 'Lisovynya38', 'Ithergue48', 'Chamassasya86',
       'Iskosia90', 'Yalae81', 'Itheria73', 'Iskjaskst81', 'Undjask33',
       'Chanosian48', 'Inguron55', 'Haisrisuir60', 'Saelaephos52',
       'Assjaskan73', 'Saesrideu94', 'Lisassa64', 'Lisirra25',
       'Zontibe81', 'Reunasu60', 'Chamalo71', 'Iathenudil29',
       'Phiarithdeu40', 'Siarithria38', 'Eyrian71', 'Siala43',
       'Lisirra87', 'Lirtossa84', 'Eusri44', 'Aela59', 'Tyida79',
       'Idai61', 'Farusrian86', 'Aeralria27', 'Haillyrgue51', 'Sondim73',
       'Jeyciman68', 'Idaisuir85', 'Seuthep89', 'Reulae52',
       'Sondilsaya62', 'Aerithriaphos45', 'Assosia88', 'Aidaillodeu39',
       'Aelly27', 'Tyeosri53', 'Haerith37', 'Yasrisu92', 'Chanuchi25',
       'Asur96', 'Iaralrgue74', 'Chanosia34', 'Aelin32', 'Ilosianya35',
       'Zhisrisu83', 'Phaelap26', 'Raesty92', 'Palyon91', 'Tyisur83',
       'Yaliru88', 'Yadanu52', 'Jiskimya77', 'Yadaphos40', 'Alo38',
       'Phaena87', 'Chamirraya83', 'Chanastsda67', 'Indonmol95',
       'Jiskossa61', 'Pheodai94', 'Hari50', 'Marilsa69', 'Assistasda42',
       'Lisosia93', 'Philodil43', 'Mindadaran26', 'Lirtosia63',
       'Assjaskan56', 'Irithlis29', 'Heudai45', 'Haerithp41', 'Aina42',
       'Jiskjask60', 'Umolrian85', 'Qarirwen82', 'Laedallo55',
       'Eoralrap26', 'Undosian34', 'Chadolyla44', 'Chadistaya75',
       'Yathedeu43', 'Aina43', 'Ilassast39', 'Lisassala98', 'Aiduecal76',
       'Chadossa89', 'Pheodaisun84', 'Heollyriap59', 'Maropast28',
       'Frichim77', 'Thryallym62', 'Eulanurin88', 'Lassjaskan73',
       'Tyaerith73', 'Sondadarya58', 'Hirirap39', 'Ririp86', 'Sundim98',
       'Iskichinya81', 'Phyali88', 'Undirrala66', 'Nitherian58',
       'Lassilsala30', 'Frichaststa61', 'Frichosia58', 'Ilosia37',
       'Lisista27', 'Seudaillorap38', 'Aesty53', 'Yathecal82',
       'Lisossanya98', 'Iral74', 'Lisast87', 'Maridisya31', 'Jiskassa76',
       'Ethriel85', 'Iskirra45', 'Iri67', 'Rarallo90', 'Lisasi93',
       'Adastirin33', 'Eyista89', 'Ili43', 'Chamirra53', 'Hailaphos89',
       'Iskadarya95', 'Qilatista90', 'Inasti31', 'Marilsanya48',
       'Marjask87', 'Chanjaskan89', 'Hyaduesu61', 'Aillyrin83',
       'Marast30', 'Sundadar27', 'Tyaelorap29', 'Lirtimst73',
       'Styaduen40', 'Sidap51', 'Chanastst38', 'Lirtassa52', 'Sondim68',
       'Aeral97', 'Heosurnuru52', 'Lisopela58', 'Caesrinusuir82',
       'Tyirinu79', 'Fironon91', 'Lassjask63', 'Indcil77', 'Chamimla73',
       'Syathe73', 'Baelollodeu94', 'Mindista32', 'Saena74',
       'Marirrasta50', 'Lamil79', 'Aenarap34', 'Aisur51', 'Thrientossa55',
       'Chadista79', 'Tyeurith29', 'Malunil62', 'Hiasri33', 'Lisadar44',
       'Frichjask31', 'Lisjaskya84', 'Ristydru66', 'Frichast28',
       'Minduri31', 'Maradaran90', 'Mindetosya30', 'Ialallo29',
       'Pheusrical25', 'Chanosia60', 'Phistym51', 'Aelollo59',
       'Chamimla85', 'Haisurra41', 'Sondastsda82', 'Qilanrion65',
       'Eulasuir89', 'Eosrirgue62', 'Shaidanu32', 'Lirtastan49',
       'Iaralsuir44', 'Tyeudariasuir90', 'Cosadar58', 'Aelastirin39',
       'Aidai53', 'Jiskjask85', 'Ealrion88', 'Chamjask73', 'Tyaenasti87',
       'Alim85', 'Haeladil46', 'Jiskirran77', 'Undosia27', 'Peorith44',
       'Yarithsurgue62', 'Taeduenu92', 'Rairin89', 'Aerithriaphos46',
       'Idairin51', 'Lisista54', 'Eodailis27', 'Lirtastsda29',
       'Undilsan50', 'Eodaisu60', 'Quaranmol58', 'Lirtossa60',
       'Lirtilsa71', 'Isursuir31', 'Sundirrala66', 'Saerallora71',
       'Iasur80', 'Tyaelo67', 'Quanunwen42', 'Yasur35', 'Assehoan67',
       'Haellysu29', 'Saida58', 'Chamadar79', 'Aeral43', 'Lirtirra37',
       'Tyidaim51', 'Lassassast73', 'Assassasta79', 'Heollyra92',
       'Anallorgue57', 'Aerithllora36', 'Smaistysu35', 'Ennalmol65',
       'Yarithrgue83', 'Yana46', 'Sondimla25', 'Aidai61', 'Wailin72',
       'Firan91', 'Alaesu91', 'Aellynun67', 'Rilaera56', 'Eulaestira36',
       'Marim28', 'Idastidru52', 'Ilirrasda54', 'Alaephos75',
       'Syalollorap93', 'Minduli80', 'Chanastya70', 'Frichadaran88',
       'Siallylis44', 'Aeri84', 'Iasursti71', 'Mindilsa34', 'Chamastya76',
       'Undirra73', 'Aestysu37', 'Chadadarla74', 'Strithenu87',
       'Iasrira89', 'Ialidru40', 'Tyalaesu89', 'Tyidainu31', 'Lirtilsa72',
       'Undjaskla97', 'Saedaiphos46', 'Aerithnucal56', 'Lisossa46',
       'Layjask75', 'Lisista63', 'Ceoral34', 'Hilaerin92',
       'Chadilsasta32', 'Undassa89', 'Iduenu77', 'Lisosia66',
       'Undimsya85', 'Phaedue89', 'Yadacal26', 'Lisossa25', 'Ilmol66',
       'Yastyriaphos75', 'Hiasurria41', 'Palatyon26', 'Qilalista41',
       'Hada39', 'Chamilsala65', 'Rairith81', 'Ilarin91', 'Ryanara76',
       'Undista85', 'Tyeoralru41', 'Pheosrinudeu70', 'Heuli25',
       'Pheutherin27', 'Chadirra90', 'Ali84', 'Frichjaskan98', 'Malil90',
       'Yarithllodeu72', 'Tyaedainu44', 'Ethron58', 'Eusurdeu49',
       'Saistyphos30', 'Saisrilis27', 'Hallysucal81', 'Ilimya66',
       'Raysistast71', 'Haedairiadru51', 'Tyananurgue44', 'Risty84',
       'Aerillorin70', 'Phistyn52', 'Yalo85', 'Chamirrasya33', 'Hiral75',
       'Isursti83', 'Bartassaya73', 'Aeda94', 'Quinarap53', 'Asur53',
       'Alarap40', 'Sida61', 'Hiarideu73', 'Lassassasda30', 'Ennoncil86',
       'Siralsudeu54', 'Eusri26', 'Ardcil81', 'Marilsasya33', 'Lirtim36',
       'Heunadil74', 'Frichadar89', 'Aesurstilis64', 'Idaidil28',
       'Lisotesta51', 'Lisico81', 'Lisiriya82', 'Siana77', 'Marokian45',
       'Sausosia74', 'Assesi91', 'Eusri70', 'Aisurria69', 'Iarilis73',
       'Raisty38', 'Ilista82', 'Leyirra83', 'Aiduesu86', 'Frichynde86',
       'Hisridru55', 'Chamossa77', 'Irillo49', 'Lirtastsya71',
       'Frichosiala98', 'Qilunan34', 'Quarrion42', 'Aisurdru79',
       'Hiaral50', 'Iarallo65', 'Sondassasya91', 'Chanossast57',
       'Chanjask65', 'Ethralista69', 'Sondistanya61', 'Eudanu32',
       'Euthe35', 'Lassimla92', 'Lisossala30', 'Eulae84', 'Chamadarnya73',
       'Eolan54', 'Assistasda90', 'Ennrian78', 'Undirrasta89',
       'Rianistast50', 'Undare39', 'Adairialis76', 'Aesur96',
       'Tyialisudeu65', 'Arirgue63', 'Sundadarla27', 'Eyircil84', 'Ina92',
       'Lirtistanya48', 'Marassa62', 'Mindossa76', 'Salilis27',
       'Sondossa69', 'Sundjask71', 'Errian63', 'Eurithphos97',
       'Raillydeu47', 'Malon70', 'Jiskimsda56', 'Marughi89', 'Ingatcil75',
       'Chanirrasta87', 'Alaesu77', 'Ermol76', 'Tyeuduen32', 'Firon67',
       'Iadueria43', 'Pheulidil31', 'Eodairu79', 'Frichocesta66',
       'Thourdirra92', 'Chanastnya43', 'Iskim96', 'Eulolis41',
       'Sastydeu50', 'Ilaesudil92', 'Yasur85', 'Aidain51',
       'Aerithnuphos61', 'Yalostiphos68', 'Meosridil82', 'Aillyriadru65',
       'Sally64', 'Lisim51', 'Isurria36', 'Silaera56', 'Leetirraya83',
       'Lirtirra81', 'Eryon48', 'Iana95', 'Sondassan80', 'Chanadar44',
       'Eosurdru76', 'Shidai42', 'Aesri53', 'Syally44', 'Jiskadarst60',
       'Sondadar26', 'Malarrian73', 'Maluncil97', 'Ilunyon70', 'Yadam35',
       'Dyally87', 'Pheosurllorin41', 'Frichaya88', 'Lassadarsda57',
       'Marynde90', 'Isri34', 'Assastnya25', 'Ardonmol96',
       'Lassirrasda85', 'Chadossa56', 'Poshilsa82', 'Yoishirrala98',
       'Sundista37', 'Ilassa51', 'Filurarn35', 'Phaestycal84', 'Irilis75',
       'Aeralstical35', 'Chanirrala39', 'Chanirra79', 'Assirra56',
       'Seolollo93', 'Iathem87', 'Iasurriacal29', 'Lisast98', 'Filrion59',
       'Halaecal66', 'Iskosian40', 'Ilastilis78', 'Seosrim97',
       'Farrian71', 'Rithe53', 'Frichossala54', 'Chamjaskya75',
       'Quanrion96', 'Tyaelaelis94', 'Quanenrian83', 'Chanirra64',
       'Yadaisuir65', 'Syathecal44', 'Arin32', 'Aelaria33', 'Assassa81',
       'Filrion83', 'Eoral49', 'Airi27', 'Eurisuru25', 'Liawista80',
       'Lisirra58', 'Chamadarsda63', 'Haestyphos66', 'Phaedasurap84',
       'Mindimnya67', 'Chadjask85', 'Eustyria89', 'Iskim66', 'Chamast86',
       'Lirtassan78', 'Ethrasyon38', 'Quilassa66', 'Lisassasda39',
       'Mindilsa60', 'Lalossa38', 'Chamistast30', 'Hariphos58',
       'Assilsan72', 'Inasuir29', 'Chanilsasda38', 'Mindesi74',
       'Ililsan66', 'Idacal95', 'Aeral68', 'Tyarithn67', 'Asty82',
       'Yalaeria91', 'Chadjask77', 'Ealiril69', 'Quaecjask96',
       'Firatan58', 'Yarolwen77', 'Tyaelistidru84', 'Yarithrin84',
       'Tyaelly53', 'Phiristi62', 'Ililsasya43', 'Aithelis62',
       'Undotesta33', 'Aelidru27', 'Chanossanya44', 'Maradarnya40',
       'Lisilsa62', 'Saena89', 'Chanilsast61', 'Sundassa93', 'Aidai73',
       'Indirrian56', 'Lisassasta50', 'Iduelis31', 'Chanosiaya39',
       'Assylla81', 'Aidaira26', 'Eudanu84', 'Chamiman85', 'Tyialisti80',
       'Marundi65', 'Eusur90', 'Mindirranya33', 'Phiallylis33', 'Isty55',
       'Frichilsa31', 'Chanista95', 'Aellyria80', 'Rastynusuir31',
       'Iljask75', 'Lisjaskan36', 'Mindjasksya61', 'Frichirranya75',
       'Ilast79', 'Eratiel90', 'Assim27', 'Irith83', 'Ilosian36',
       'Iskossasda43', 'Hala31', 'Jiskjask80', 'Aethedru70', 'Yathecal72',
       'Sisur91'], dtype=object)

In [24]:
group_sn = purchase_data_df.groupby("SN")
group_sn.head()

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44
5,5,Yalae81,22,Male,81,Dreamkiss,3.61
6,6,Itheria73,36,Male,169,"Interrogator, Blood Blade of the Queen",2.18
7,7,Iskjaskst81,20,Male,162,Abyssal Shard,2.67
8,8,Undjask33,22,Male,21,Souleater,1.10
9,9,Chanosian48,35,Other / Non-Disclosed,136,Ghastly Adamantite Protector,3.58
10,10,Inguron55,23,Male,95,Singed Onyx Warscythe,4.74
11,11,Haisrisuir60,23,Male,162,Abyssal Shard,2.67
12,12,Saelaephos52,21,Male,116,Renewed Skeletal Katana,4.18
13,13,Assjaskan73,22,Male,4,Bloodlord's Fetish,1.70
14,14,Saesrideu94,35,Male,165,Bone Crushing Silver Skewer,4.86
15,15,Lisassa64,21,Female,98,"Deadline, Voice Of Subtlety",2.89
16,16,Lisirra25,20,Male,40,Second Chance,2.52
17,17,Zontibe81,21,Male,161,Devine,1.76
18,18,Reunasu60,22,Female,82,Nirvana,4.90
19,19,Chamalo71,30,Male,89,"Blazefury, Protector of Delusions",4.64
20,20,Iathenudil29,20,Male,57,"Despair, Favor of Due Diligence",4.60
21,21,Phiarithdeu40,20,Male,168,"Sun Strike, Jaws of Twisted Visions",1.48
22,22,Siarithria38,38,Other / Non-Disclosed,24,Warped Fetish,3.81
23,23,Eyrian71,40,Male,151,Severance,3.40
24,24,Siala43,30,Male,141,Persuasion,3.19
25,25,Lisirra87,29,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23
26,26,Lirtossa84,11,Male,71,Demise,1.61
27,27,Eusri44,7,Male,96,Blood-Forged Skeletal Spine,3.09
28,28,Aela59,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",4.32
29,29,Tyida79,24,Male,37,"Shadow Strike, Glory of Ending Hope",3.16
...,...,...,...,...,...,...,...
750,750,Iljask75,22,Male,167,"Malice, Legacy of the Queen",3.61
751,751,Lisjaskan36,11,Male,180,Stormcaller,3.36
752,752,Mindjasksya61,17,Male,112,Worldbreaker,2.60
753,753,Frichirranya75,36,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23
754,754,Pheosurllorin41,23,Female,79,"Alpha, Oath of Zeal",4.05
755,755,Raesty92,12,Male,76,Haunted Bronzed Bludgeon,3.15
756,756,Ilast79,20,Male,73,Ritual Mace,2.05
757,757,Eratiel90,18,Male,57,"Despair, Favor of Due Diligence",4.60
758,758,Iral74,21,Male,182,Toothpick,4.03
759,759,Tyaelorap29,25,Male,72,Winter's Bite,3.77
760,760,Aithelis62,21,Male,44,Bonecarvin Battle Axe,2.38
761,761,Assim27,45,Male,17,"Lazarus, Terror of the Earth",1.70
762,762,Asur53,26,Male,110,Suspension,1.44
763,763,Lassilsala30,21,Male,85,Malificent Bag,1.75
764,764,Saedaiphos46,18,Male,113,Solitude's Reaver,4.07
765,765,Irith83,18,Male,130,Alpha,2.07
766,766,Aelastirin39,23,Male,58,"Freak's Bite, Favor of Holy Might",4.14
767,767,Ilmol66,8,Female,92,Final Critic,4.88
768,768,Assassasta79,38,Male,92,Final Critic,4.88
769,769,Ilosian36,15,Male,145,Fiery Glass Crusader,4.58
770,770,Lirtosia63,34,Male,12,Dawne,1.02
771,771,Iskossasda43,16,Male,25,Hero Cane,4.35
772,772,Asur53,26,Male,136,Ghastly Adamantite Protector,3.58
773,773,Hala31,21,Male,19,"Pursuit, Cudgel of Necromancy",1.02
774,774,Jiskjask80,11,Male,101,Final Critic,4.19
775,775,Aethedru70,21,Female,60,Wolf,3.54
776,776,Iral74,21,Male,164,Exiled Doomblade,1.63
777,777,Yathecal72,20,Male,67,"Celeste, Incarnation of the Corrupted",3.46
778,778,Sisur91,7,Male,101,Final Critic,4.19
779,779,Ennrian78,24,Male,50,Dawn,4.60

In [25]:
count_players = purchase_data_df.loc[:,["SN"]]
count_players

                  SN
0            Lisim78
1        Lisovynya38
2         Ithergue48
3      Chamassasya86
4          Iskosia90
5            Yalae81
6          Itheria73
7        Iskjaskst81
8          Undjask33
9        Chanosian48
10         Inguron55
11      Haisrisuir60
12      Saelaephos52
13       Assjaskan73
14       Saesrideu94
15         Lisassa64
16         Lisirra25
17         Zontibe81
18         Reunasu60
19         Chamalo71
20      Iathenudil29
21     Phiarithdeu40
22      Siarithria38
23          Eyrian71
24           Siala43
25         Lisirra87
26        Lirtossa84
27           Eusri44
28            Aela59
29           Tyida79
..               ...
750         Iljask75
751      Lisjaskan36
752    Mindjasksya61
753   Frichirranya75
754  Pheosurllorin41
755         Raesty92
756          Ilast79
757        Eratiel90
758           Iral74
759      Tyaelorap29
760       Aithelis62
761          Assim27
762           Asur53
763     Lassilsala30
764     Saedaiphos46
765          Irith83
766     Aelastirin39
767          Ilmol66
768     Assassasta79
769        Ilosian36
770       Lirtosia63
771     Iskossasda43
772           Asur53
773           Hala31
774       Jiskjask80
775       Aethedru70
776           Iral74
777       Yathecal72
778          Sisur91
779        Ennrian78

[780 rows x 1 columns]

In [26]:
count_players = count_players.drop_duplicates()
count_players.count()

SN    576
dtype: int64

In [27]:
count_players = pd.DataFrame({
    "Total Players":count_players.count()})
count_players

    Total Players
SN            576

## Purchasing Analysis (Total)

* Run basic calculations to obtain number of unique items, average price, etc.


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [31]:
unique_items = len(purchase_data_df["Item ID"].value_counts())

total_revenue = round(purchase_data_df["Price"].sum(), 2)

num_purchases = purchase_data_df["Price"].count()

average_price = round(purchase_data_df["Price"].mean(), 2)

purchase_analysis = []

purchase_analysis.append(unique_items)
purchase_analysis.append("$" + str(average_price))
purchase_analysis.append(num_purchases)
purchase_analysis.append("$" + str(total_revenue))

pd.DataFrame([purchase_analysis], columns = ["Number of Unique Items", "Average Price", "Number of Purchases", "Total Revenue"])

   Number of Unique Items Average Price  Number of Purchases Total Revenue
0                     183         $3.05                  780      $2379.77

## Gender Demographics

* Percentage and Count of Male Players


* Percentage and Count of Female Players


* Percentage and Count of Other / Non-Disclosed

In [38]:
gender_grouped = purchase_data_df[["SN", "Gender"]]
gender_grouped = gender_grouped.drop_duplicates()
counts = gender_grouped["Gender"].value_counts()

################################
total_counts = [counts[0],counts[1],counts[2]]
percents_g = [round((counts[0]/player_count)*100,2),round((counts[1]/player_count)*100,2),round((counts[2]/player_count)*100,2)]

total_counts

[484, 81, 11]

In [39]:
gender_demo_df = pd.DataFrame({
    "Total Count": total_counts,
    "Percentage of Players": percents_g})
gender_demo_df.index = (["Male", "Female", "Other / Non-Disclosed"])
gender_demo_df

,Total Count,Percentage of Players
Male,484,Lisosia93 9680.00 Idastidru52 121...
Female,81,Lisosia93 1620.0 Idastidru52 2025....
Other / Non-Disclosed,11,Lisosia93 220.00 Idastidru52 275...


## Purchasing Analysis (Gender)

* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. by gender




* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [33]:
gender_grouped = purchase_data_df[["SN","Gender","Price"]]
counts_g = gender_grouped["Gender"].value_counts()

purchase_counts = [counts_g[0],counts_g[1],counts_g[2]]

gender_grouped = gender_grouped.groupby("Gender")
total_spent = gender_grouped.sum()
total_spent

total_purchase_value_g = [total_spent.iloc[1,0], total_spent.iloc[0,0], total_spent.iloc[2,0]]

avg_purchase_g = [total_spent.iloc[1,0]/counts_g[0], total_spent.iloc[0,0]/counts_g[1], total_spent.iloc[2,0]/counts_g[2]]

norm_tot_g = [total_spent.iloc[1,0]/counts[0], total_spent.iloc[0,0]/counts[1], total_spent.iloc[2,0]/counts[2]]

purchase_analysis_g_df = pd.DataFrame({
    "Purchase Count": purchase_counts,
    "Average Purchase Price": avg_purchase_g,
    "Total Purchase Value": total_purchase_value_g,
    "Normalized Totals": norm_tot_g,
    "Gender": ["Male", "Female", "Other / Non-Disclosed"]})
purchase_analysis_g_df = purchase_analysis_g_df.set_index("Gender")
purchase_analysis_g_df = purchase_analysis_g_df[["Purchase Count", "Average Purchase Price", "Total Purchase Value",
                                                 "Normalized Totals"]]

purchase_analysis_g_df.style.format({"Average Purchase Price": "${:.2f}", "Normalized Totals": "${:.2f}",
                                     "Total Purchase Value":"${:.2f}"})

## Age Demographics

* Establish bins for ages


* Categorize the existing players using the age bins. Hint: use pd.cut()


* Calculate the numbers and percentages by age group


* Create a summary data frame to hold the results


* Optional: round the percentage column to two decimal points


* Display Age Demographics Table

In [41]:
age_df = purchase_data_df[["SN","Age"]]
age_df = age_df.drop_duplicates()

age_df

                 SN  Age
0           Lisim78   20
1       Lisovynya38   40
2        Ithergue48   24
3     Chamassasya86   24
4         Iskosia90   23
5           Yalae81   22
6         Itheria73   36
7       Iskjaskst81   20
8         Undjask33   22
9       Chanosian48   35
10        Inguron55   23
11     Haisrisuir60   23
12     Saelaephos52   21
13      Assjaskan73   22
14      Saesrideu94   35
15        Lisassa64   21
16        Lisirra25   20
17        Zontibe81   21
18        Reunasu60   22
19        Chamalo71   30
20     Iathenudil29   20
21    Phiarithdeu40   20
22     Siarithria38   38
23         Eyrian71   40
24          Siala43   30
25        Lisirra87   29
26       Lirtossa84   11
27          Eusri44    7
28           Aela59   21
29          Tyida79   24
..              ...  ...
728    Chanosiaya39   44
729       Assylla81   20
730       Aidaira26   30
731        Eudanu84   22
733      Chamiman85   20
736     Tyialisti80   23
737       Marundi65   22
738         Eusur90   36
739   Mindirranya33   35
741    Phiallylis33   19
742          Isty55   20
743     Frichilsa31   15
745      Chanista95   39
746      Aellyria80   23
748   Rastynusuir31   20
750        Iljask75   22
751     Lisjaskan36   11
752   Mindjasksya61   17
753  Frichirranya75   36
756         Ilast79   20
757       Eratiel90   18
761         Assim27   45
765         Irith83   18
769       Ilosian36   15
771    Iskossasda43   16
773          Hala31   21
774      Jiskjask80   11
775      Aethedru70   21
777      Yathecal72   20
778         Sisur91    7

[576 rows x 2 columns]

## Purchasing Analysis (Age)

* Bin the purchase_data data frame by age


* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. in the table below


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

## Top Spenders

* Run basic calculations to obtain the results in the table below


* Create a summary data frame to hold the results


* Sort the total purchase value column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

## Most Popular Items

* Retrieve the Item ID, Item Name, and Item Price columns


* Group by Item ID and Item Name. Perform calculations to obtain purchase count, item price, and total purchase value


* Create a summary data frame to hold the results


* Sort the purchase count column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

## Most Profitable Items

* Sort the above table by total purchase value in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the data frame